drop table if exists endereco
create table  endereco (id integer generated by default as identity, cep_cli varchar(10) not null unique, bairro varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));

drop table if exists tb_cliente
create table tb_cliente (ativo_cli boolean, id_cli integer generated by default as identity, id_endereco integer not null, cpf_cli varchar(11) not null unique, telefone_cli varchar(20) not null, email_cli varchar(255), nome_cli varchar(255), perfil varchar(255), senha_cli varchar(255), primary key (id_cli));

drop table if exists tb_equipamento
create table tb_equipamento (ativo_equip boolean not null, id_equip integer generated by default as identity, nome_equip varchar(255) not null unique, primary key (id_equip));

drop table if exists tb_funcionario
create table tb_funcionario (ativo_func boolean, datanasc_func date not null, id_func integer generated by default as identity, email_func varchar(255), nome_func varchar(255), perfil varchar(255), senha_func varchar(255), primary key (id_func));

drop table if exists tb_historico
create table tb_historico (func_hist integer not null, id_hist integer generated by default as identity, soli_hist integer not null, dt_registro timestamp(6), primary key (id_hist));

drop table if exists tb_pagamento
create table tb_pagamento (id_pag integer generated by default as identity, soli_pag integer not null, valor_pag float(53) not null, dt_pagamento timestamp(6), forma_pag varchar(20) not null, primary key (id_pag));

drop table if exists tb_solicitacao
create table tb_solicitacao (eletronico_soli integer, funcionario_soli integer, id_soli integer generated by default as identity, valor_soli float(53), dt_inicio timestamp(6), cliente_soli varchar(255), desc_soli varchar(255), estado_soli varchar(255), nome_soli varchar(255), orientacoe_soli varchar(255), primary key (id_soli));

alter table if exists tb_cliente add constraint FK3cc1k2yo470a56vk42x0rb12x foreign key (id_endereco) references endereco;
